language: bash

# Try a large OS matrix because the goal is compatibility
# https://docs.travis-ci.com/user/reference/overview/
matrix:
  include:
    - os: linux
      dist: precise
    - os: osx
    - os: linux
      dist: trusty
  python: "3.7"
  perl:   "5.26-shrplib"
before_install:
  # Install very specific versions of libraries
  # because this project relies on versioning.
  - pip install --user biopython==1.72
  - curl -L https://cpanmin.us/ -o $HOME/cpanm
  - yes no | $HOME/cpanm --force --notest -l $HOME "C/CJ/CJFIELDS/BioPerl-1.007001.tar.gz"
  - export PERL5LIB=$PERL5LIB:$HOME/lib/perl5

script: bash tests/alltests.sh 

